// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwMoxRm71RBa-n_LUSNYNGi0ROp_u2diY',
    appId: '1:693983938079:web:45278f0f031f2347c1b72a',
    messagingSenderId: '693983938079',
    projectId: 'mybooks-2f6c0',
    authDomain: 'mybooks-2f6c0.firebaseapp.com',
    databaseURL: 'https://mybooks-2f6c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybooks-2f6c0.firebasestorage.app',
    measurementId: 'G-CSEGBXPC13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU7Fiq-CYaYmv6r_1SRNs7oi5gk4mTsPs',
    appId: '1:693983938079:android:c1517adf088fb5d3c1b72a',
    messagingSenderId: '693983938079',
    projectId: 'mybooks-2f6c0',
    databaseURL: 'https://mybooks-2f6c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybooks-2f6c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAREBR6UoKVpq7TZwDG-4dqDbjR7Hhyxcw',
    appId: '1:693983938079:ios:fa70c06fb2e0e1c1c1b72a',
    messagingSenderId: '693983938079',
    projectId: 'mybooks-2f6c0',
    databaseURL: 'https://mybooks-2f6c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybooks-2f6c0.firebasestorage.app',
    iosBundleId: 'com.example.myBooks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAREBR6UoKVpq7TZwDG-4dqDbjR7Hhyxcw',
    appId: '1:693983938079:ios:fa70c06fb2e0e1c1c1b72a',
    messagingSenderId: '693983938079',
    projectId: 'mybooks-2f6c0',
    databaseURL: 'https://mybooks-2f6c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybooks-2f6c0.firebasestorage.app',
    iosBundleId: 'com.example.myBooks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwMoxRm71RBa-n_LUSNYNGi0ROp_u2diY',
    appId: '1:693983938079:web:bd787cc9c5614ec0c1b72a',
    messagingSenderId: '693983938079',
    projectId: 'mybooks-2f6c0',
    authDomain: 'mybooks-2f6c0.firebaseapp.com',
    databaseURL: 'https://mybooks-2f6c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybooks-2f6c0.firebasestorage.app',
    measurementId: 'G-6DSC63H51P',
  );

}